runtime: python
env: flex
runtime_config:
    python_version: 3.7

manual_scaling:
  instances: 2
resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 20  # Disk size must be between 10GB and 10240GB

entrypoint: gunicorn -b :$PORT app:flask_app --timeout 300